from pathlib import Path

# --- market.py ---
p = Path('market.py')
s = p.read_text(encoding='utf-8')

# Structural target selector: keep a floor, allow no upper RR ceiling.
s = s.replace('''    max_rr: float,\n) -> tuple[float | None, float | None]:''', '''    max_rr: float | None,\n) -> tuple[float | None, float | None]:''', 1)
s = s.replace('''        if min_rr <= rr <= max_rr:\n            tp1_index = index\n            break''', '''        if rr >= min_rr and (max_rr is None or rr <= max_rr):\n            tp1_index = index\n            break''', 1)
s = s.replace('''            max_rr=4.0,\n''', '''            max_rr=None,\n''')
s = s.replace('''            "BULLISH", 2.0, 4.0,\n''', '''            "BULLISH", 2.0, None,\n''')
s = s.replace('''            "BEARISH", 2.0, 4.0,\n''', '''            "BEARISH", 2.0, None,\n''')
s = s.replace('''            "BULLISH", 2.5, 4.0,\n''', '''            "BULLISH", 2.0, None,\n''')

# SWING RR floor only.
s = s.replace("(rr_check < 2.0 or rr_check > 4.0), 'rr_check < 2.0 or rr_check > 4.0', 'rr_check < 2.0 or rr_check > 4.0'", "(rr_check < 2.0), 'rr_check < 2.0', 'rr_check < 2.0'", 1)
s = s.replace("'rr_check < 2.0 or rr_check > 4.0', locals(), 'rr_check < 2.0 or rr_check > 4.0'", "'rr_check < 2.0', locals(), 'rr_check < 2.0'", 1)

# WYCKOFF all variants: RR >= 2, no upper cap.
s = s.replace("(risk == 0 or not 2.0 <= reward / risk <= 4.0), 'risk == 0 or not 2.0 <= reward / risk <= 4.0', 'risk == 0 or not 2.0 <= reward / risk <= 4.0'", "(risk == 0 or reward / risk < 2.0), 'risk == 0 or reward / risk < 2.0', 'risk == 0 or reward / risk < 2.0'")
s = s.replace("'risk == 0 or not 2.0 <= reward / risk <= 4.0', locals(), 'risk == 0 or not 2.0 <= reward / risk <= 4.0'", "'risk == 0 or reward / risk < 2.0', locals(), 'risk == 0 or reward / risk < 2.0'")
s = s.replace("(not 2.5 <= rr <= 4.0), 'not 2.5 <= rr <= 4.0', 'not 2.5 <= rr <= 4.0'", "(rr < 2.0), 'rr < 2.0', 'rr < 2.0'", 1)
s = s.replace("'not 2.5 <= rr <= 4.0', locals(), 'not 2.5 <= rr <= 4.0'", "'rr < 2.0', locals(), 'rr < 2.0'", 1)
s = s.replace('f"- RR={rr} < 2.5\\n"', 'f"- RR={rr} < 2.0\\n"')

# FAST RR floor only.
s = s.replace("(not 2.0 <= rr <= 4.0), 'not 2.0 <= rr <= 4.0', 'not 2.0 <= rr <= 4.0'", "(rr < 2.0), 'rr < 2.0', 'rr < 2.0'", 1)
s = s.replace("'not 2.0 <= rr <= 4.0', locals(), 'not 2.0 <= rr <= 4.0'", "'rr < 2.0', locals(), 'rr < 2.0'", 1)

# FAST: replace HTF-led direction with tested Balanced LTF-primary context.
old_context = '''        # ── 1. BTC направление ──\n        btc_candles_1h = get_candles("BTCUSDT", "1h", 10)\n        btc_trend = "BULLISH" if btc_candles_1h and btc_candles_1h[-1]["close"] > btc_candles_1h[-3]["close"] else "BEARISH"\n\n        # ── 2. 4h+1h consensus (мягкий — один из двух достаточно) ──\n        direction_4h = smc_on_tf(symbol, "4h")\n        direction_1h = smc_on_tf(symbol, "1h")\n        if _audit_test('FAST_DETECT_FAST_DEAL_G9148', (not direction_4h and not direction_1h), '2. 4h+1h consensus (мягкий — один из двух достаточно)', 'not direction_4h and not direction_1h', 9148):\n            return _audit_fail('FAST_DETECT_FAST_DEAL_R9149', '2. 4h+1h consensus (мягкий — один из двух достаточно)', locals(), 'not direction_4h and not direction_1h', 9149)\n        # Берём направление: приоритет 4h, fallback 1h\n        direction_1d = direction_4h or direction_1h\n        # Для редкого скальпа не берём конфликтующие 4h/1h направления.\n        if _audit_test('FAST_DETECT_FAST_DEAL_G9153', (direction_4h and direction_1h and direction_4h != direction_1h), 'Для редкого скальпа не берём конфликтующие 4h/1h направления.', 'direction_4h and direction_1h and direction_4h != direction_1h', 9153):\n            return _audit_fail('FAST_DETECT_FAST_DEAL_R9154', 'Для редкого скальпа не берём конфликтующие 4h/1h направления.', locals(), 'direction_4h and direction_1h and direction_4h != direction_1h', 9154)\n\n        # BTC фильтр: только для альткоинов — BTCUSDT не фильтруем через себя\n        if symbol != 'BTCUSDT':\n            if _audit_test('FAST_DETECT_FAST_DEAL_G9158', (direction_1d == "BULLISH" and btc_trend == "BEARISH"), 'BTC фильтр: только для альткоинов — BTCUSDT не фильтруем через себя', 'direction_1d == "BULLISH" and btc_trend == "BEARISH"', 9158):\n                return _audit_fail('FAST_DETECT_FAST_DEAL_R9159', 'BTC фильтр: только для альткоинов — BTCUSDT не фильтруем через себя', locals(), 'direction_1d == "BULLISH" and btc_trend == "BEARISH"', 9159)\n            if direction_1d == 'BEARISH' and btc_trend == 'BULLISH':\n                try:\n                    btc_change = (btc_candles_1h[-1]["close"] - btc_candles_1h[-4]["close"]) / btc_candles_1h[-4]["close"] * 100\n                    if _audit_test('FAST_DETECT_FAST_DEAL_G9163', (btc_change > 1.0), 'BTC фильтр: только для альткоинов — BTCUSDT не фильтруем через себя', 'btc_change > 1.0', 9163):\n                        return _audit_fail('FAST_DETECT_FAST_DEAL_R9164', 'btc_change > 1.0', locals(), 'btc_change > 1.0', 9164)  # BTC растёт >1% — шорт альт опасен\n                except Exception:\n                    pass\n\n        direction = direction_1d\n'''
new_context = '''        # ── 1. 15m creates the FAST thesis; 1h/4h/BTC are context only. ──\n        _fast_context_15m = get_confirmed_candles(get_candles(symbol, "15m", 61))\n        if _audit_test('FAST_LTF_CONTEXT_DATA', (not _fast_context_15m or len(_fast_context_15m) < 30), 'FAST: enough closed 15m context', 'not _fast_context_15m or len(_fast_context_15m) < 30', 9142):\n            return _audit_fail('FAST_LTF_CONTEXT_R_DATA', 'FAST: enough closed 15m context', locals(), 'not _fast_context_15m or len(_fast_context_15m) < 30', 9142)\n        _fast_bull_event = get_bos_choch_event(_fast_context_15m, "BULLISH", lookback=15, max_break_age=4)\n        _fast_bear_event = get_bos_choch_event(_fast_context_15m, "BEARISH", lookback=15, max_break_age=4)\n        if _audit_test('FAST_LTF_CONTEXT_STRUCTURE', (bool(_fast_bull_event) == bool(_fast_bear_event)), 'FAST: one fresh 15m BOS/CHoCH direction', 'bool(_fast_bull_event) == bool(_fast_bear_event)', 9145):\n            return _audit_fail('FAST_LTF_CONTEXT_R_STRUCTURE', 'FAST: one fresh 15m BOS/CHoCH direction', locals(), 'bool(_fast_bull_event) == bool(_fast_bear_event)', 9145)\n        direction = "BULLISH" if _fast_bull_event else "BEARISH"\n\n        # Balanced replay winner: at least one pair HTF supports the 15m thesis.\n        direction_4h = smc_on_tf(symbol, "4h")\n        direction_1h = smc_on_tf(symbol, "1h")\n        _fast_htf_support = direction_1h == direction or direction_4h == direction\n        if _audit_test('FAST_HTF_SUPPORT', (not _fast_htf_support), 'FAST: 1h or 4h supports 15m direction', 'not _fast_htf_support', 9150):\n            return _audit_fail('FAST_HTF_R_SUPPORT', 'FAST: 1h or 4h supports 15m direction', locals(), 'not _fast_htf_support', 9150)\n\n        # BTC is a macro veto only when both BTC 1h and 4h agree against the trade.\n        btc_direction_1h = smc_on_tf("BTCUSDT", "1h")\n        btc_direction_4h = smc_on_tf("BTCUSDT", "4h")\n        btc_trend = btc_direction_1h or btc_direction_4h or "NEUTRAL"\n        if symbol != 'BTCUSDT':\n            _fast_btc_hard_conflict = (\n                btc_direction_1h is not None and btc_direction_4h is not None\n                and btc_direction_1h == btc_direction_4h and btc_direction_1h != direction\n            )\n            if _audit_test('FAST_BTC_HARD_CONFLICT', _fast_btc_hard_conflict, 'FAST: BTC 1h+4h both oppose 15m thesis', '_fast_btc_hard_conflict', 9158):\n                return _audit_fail('FAST_BTC_R_HARD_CONFLICT', 'FAST: BTC 1h+4h both oppose 15m thesis', locals(), '_fast_btc_hard_conflict', 9158)\n\n        direction_1d = direction_1h or direction_4h or direction\n'''
if old_context not in s:
    raise SystemExit('FAST HTF-led context block not found')
s = s.replace(old_context, new_context, 1)

# 4h zone and premium/discount stay context; they no longer veto a valid 15m setup.
s = s.replace('''        if _audit_test('FAST_DETECT_FAST_DEAL_G9224', (not in_zone), 'not in_zone', 'not in_zone', 9224):\n            return _audit_fail('FAST_DETECT_FAST_DEAL_R9225', 'not in_zone', locals(), 'not in_zone', 9225)\n''', '''        _fast_4h_zone_context = bool(in_zone)\n''', 1)
s = s.replace('''        if _audit_test('FAST_DETECT_FAST_DEAL_G9237', (not _no_middle_ok), 'not _no_middle_ok', 'not _no_middle_ok', 9237):\n            return _audit_fail('FAST_DETECT_FAST_DEAL_R9238', 'not _no_middle_ok', locals(), 'not _no_middle_ok', 9238)\n''', '''        _fast_pd_context = bool(_no_middle_ok)\n''', 1)

# Add mandatory 15m OB/FVG retest after ATR is known, before the trigger search.
anchor = '''        atr_15m = sum(c["high"] - c["low"] for c in candles_15m[-14:]) / 14\n        engulfing_found = False\n'''
insert = '''        atr_15m = sum(c["high"] - c["low"] for c in candles_15m[-14:]) / 14\n\n        # LTF location is mandatory: recent retest of a real 15m OB/FVG.\n        _fast_ob_15m = find_ob(candles_15m, direction)\n        _fast_fvg_15m = find_fvg(candles_15m, direction)\n        _fast_zone_15m = _fast_ob_15m or _fast_fvg_15m\n        if _audit_test('FAST_LTF_ZONE', (not _fast_zone_15m), 'FAST: 15m OB/FVG zone exists', 'not _fast_zone_15m', 9260):\n            return _audit_fail('FAST_LTF_R_ZONE', 'FAST: 15m OB/FVG zone exists', locals(), 'not _fast_zone_15m', 9260)\n        _fast_zone_bottom = float(_fast_zone_15m["bottom"])\n        _fast_zone_top = float(_fast_zone_15m["top"])\n        _fast_zone_tol = atr_15m * 0.20\n        _fast_ltf_retest = any(\n            float(c["low"]) <= _fast_zone_top + _fast_zone_tol\n            and float(c["high"]) >= _fast_zone_bottom - _fast_zone_tol\n            for c in candles_15m[-8:]\n        )\n        if _audit_test('FAST_LTF_RETEST', (not _fast_ltf_retest), 'FAST: recent 15m OB/FVG retest', 'not _fast_ltf_retest', 9261):\n            return _audit_fail('FAST_LTF_R_RETEST', 'FAST: recent 15m OB/FVG retest', locals(), 'not _fast_ltf_retest', 9261)\n        _fast_ltf_zone_type = "OB" if _fast_ob_15m else "FVG"\n        zone_desc = f"15m {_fast_ltf_zone_type} ${_fast_zone_bottom:.4f}–${_fast_zone_top:.4f}"\n\n        engulfing_found = False\n'''
if anchor not in s:
    raise SystemExit('FAST ATR anchor not found')
s = s.replace(anchor, insert, 1)

# The tested LTF-primary design requires retest+trigger; 4h acceptance is contextual, not a second veto.
old_accept_start = '''        # ── Acceptance — проверяем на свече engulfing (не текущей) ──\n        _eng_idx = _sweep_candles_ago if '_sweep_candles_ago' in dir() else 1\n        _eng_candle = candles_15m[-_eng_idx] if _eng_idx < len(candles_15m) else candles_15m[-1]\n        if ob_4h and direction == "BULLISH":\n            _acceptance = _eng_candle["close"] > ob_4h["top"]\n        elif ob_4h and direction == "BEARISH":\n            _acceptance = _eng_candle["close"] < ob_4h["bottom"]\n        elif fvg_4h and direction == "BULLISH":\n            _acceptance = _eng_candle["close"] > fvg_4h["top"]\n        elif fvg_4h and direction == "BEARISH":\n            _acceptance = _eng_candle["close"] < fvg_4h["bottom"]\n        else:\n            _acceptance = False\n\n        if _audit_test('FAST_DETECT_FAST_DEAL_G9320', (not _acceptance), 'not _acceptance', 'not _acceptance', 9320):\n            logging.debug(f"[FAST] {symbol}: нет acceptance — цена не закрылась за зоной")\n            return _audit_fail('FAST_DETECT_FAST_DEAL_R9322', 'not _acceptance', locals(), 'not _acceptance', 9322)\n'''
new_accept = '''        # The 4h zone is context only. Execution acceptance is the confirmed\n        # 15m OB/FVG retest plus the displacement/engulfing trigger above.\n        _eng_idx = _sweep_candles_ago if '_sweep_candles_ago' in dir() else 1\n        _eng_candle = candles_15m[-_eng_idx] if _eng_idx < len(candles_15m) else candles_15m[-1]\n        _acceptance = bool(_fast_ltf_retest and engulfing_found)\n'''
if old_accept_start not in s:
    raise SystemExit('FAST 4h acceptance block not found')
s = s.replace(old_accept_start, new_accept, 1)

# Update FAST legacy prompt/evidence to match actual architecture.
s = s.replace('''                "2. 4h OB или FVG подтверждает зону — институционалы там входили\\n"''', '''                "2. 15m OB/FVG retest задаёт реальную LTF зону входа\\n"''', 1)
s = s.replace('''                "4. Acceptance — цена закрылась за зоной OB/FVG\\n"''', '''                "4. 4h/1h используются как контекст; хотя бы один HTF поддерживает 15m\\n"''', 1)
s = s.replace('''                "- Нет OB и нет FVG на 4h — вход без подтверждения зоны\\n"''', '''                "- Нет свежего 15m OB/FVG retest — вход без LTF локации\\n"''', 1)
s = s.replace('''                "- 1d тренд ПРОТИВ направления\\n"\n                "- BTC тренд ПРОТИВ направления\\n"''', '''                "- Ни 1h, ни 4h не поддерживает 15m направление\\n"\n                "- BTC 1h и 4h одновременно направлены против сделки\\n"''', 1)
s = s.replace('''                "- 4h OB или FVG подтверждает зону входа\\n"''', '''                "- Есть свежий 15m OB/FVG retest\\n"''', 1)
s = s.replace('''                "- 1d тренд и BTC в том же направлении\\n"''', '''                "- 1h или 4h поддерживает 15m, без двойного BTC-конфликта\\n"''', 1)

# Return LTF zone evidence; preserve 4h context separately.
s = s.replace('''            "ob":        ob_4h,\n            "fvg":       fvg_4h,\n            "fast_score": 0,\n''', '''            "ob":        _fast_ob_15m,\n            "fvg":       _fast_fvg_15m,\n            "htf_ob":    ob_4h,\n            "htf_fvg":   fvg_4h,\n            "htf_1h":    direction_1h,\n            "htf_4h":    direction_4h,\n            "btc_1h":    btc_direction_1h,\n            "btc_4h":    btc_direction_4h,\n            "fast_score": 0,\n''', 1)

p.write_text(s, encoding='utf-8')

# --- signal_integrity.py: universal RR floor 2.0 ---
p = Path('core/signal_integrity.py')
s = p.read_text(encoding='utf-8')
s = s.replace('''            min_rr = 2.5 if strategy in {"SWING", "WYCKOFF"} else 2.0\n''', '''            min_rr = 2.0\n''', 1)
p.write_text(s, encoding='utf-8')

# --- setup_evidence.py: no RR ceiling; FAST core is LTF location, HTF is context ---
p = Path('core/setup_evidence.py')
s = p.read_text(encoding='utf-8')
s = s.replace('''    "FAST": {"core": "session-qualified 4h OB/FVG location", "trigger": "15m displacement and fresh BOS/CHoCH"},''', '''    "FAST": {"core": "session-qualified 15m OB/FVG retest with supportive HTF context", "trigger": "15m displacement and fresh BOS/CHoCH"},''', 1)
s = s.replace('''    if rr < 2.0 or rr > 4.05:\n        return False, "RR is outside the strategy safety envelope"''', '''    if rr < 2.0:\n        return False, "RR is below the universal 2.0 minimum"''', 1)
s = s.replace('''        if location: core.append("4h OB/FVG location and session setup are present")\n        else:\n            missing.append("4h OB/FVG location")''', '''        if location: core.append("15m OB/FVG retest location and session setup are present")\n        else:\n            missing.append("15m OB/FVG retest location")''', 1)
p.write_text(s, encoding='utf-8')

# --- regression tests ---
p = Path('tests/test_rr_floor_fast_balanced.py')
p.write_text('''import unittest\nfrom pathlib import Path\n\nfrom core.signal_integrity import validate_candidate\nfrom core.setup_evidence import _geometry\n\n\nclass RRFloorFastBalancedTests(unittest.TestCase):\n    @classmethod\n    def setUpClass(cls):\n        cls.market = Path("market.py").read_text(encoding="utf-8")\n        cls.evidence = Path("core/setup_evidence.py").read_text(encoding="utf-8")\n\n    def test_rr_above_four_is_valid_for_every_strategy_integrity(self):\n        for strategy in ("MTF", "SWING", "ZONE", "FAST", "WYCKOFF"):\n            candidate = {\n                "symbol": "ETHUSDT", "direction": "BULLISH", "scan_type": strategy,\n                "entry": 100.0, "sl": 99.0, "tp1": 105.0, "tp2": 106.0, "tp3": 107.0, "rr": 5.0,\n            }\n            with self.subTest(strategy=strategy):\n                self.assertTrue(validate_candidate(candidate)["valid"])\n\n    def test_rr_below_two_is_rejected(self):\n        candidate = {"symbol":"ETHUSDT","direction":"BULLISH","scan_type":"MTF","entry":100,"sl":99,"tp1":101.9,"rr":1.9}\n        self.assertFalse(validate_candidate(candidate)["valid"])\n        self.assertFalse(_geometry(candidate, "BULLISH")[0])\n\n    def test_setup_evidence_accepts_rr_above_four(self):\n        candidate = {"entry":100,"sl":99,"tp1":105,"rr":5.0}\n        self.assertTrue(_geometry(candidate, "BULLISH")[0])\n\n    def test_all_active_strategy_rr_caps_removed(self):\n        forbidden = [\n            "rr_check < 2.0 or rr_check > 4.0",\n            "not 2.0 <= rr <= 4.0",\n            "not 2.5 <= rr <= 4.0",\n            "not 2.0 <= reward / risk <= 4.0",\n            "max_rr=4.0",\n        ]\n        for text in forbidden:\n            self.assertNotIn(text, self.market)\n        self.assertIn("max_rr=None", self.market)\n\n    def test_fast_is_ltf_primary_balanced_context(self):\n        self.assertIn('FAST: one fresh 15m BOS/CHoCH direction', self.market)\n        self.assertIn('FAST: 1h or 4h supports 15m direction', self.market)\n        self.assertIn('FAST: recent 15m OB/FVG retest', self.market)\n        self.assertIn('FAST: BTC 1h+4h both oppose 15m thesis', self.market)\n        self.assertNotIn("return _audit_fail('FAST_DETECT_FAST_DEAL_R9225'", self.market)\n        self.assertNotIn("return _audit_fail('FAST_DETECT_FAST_DEAL_R9238'", self.market)\n\n    def test_fast_quality_guards_still_exist(self):\n        self.assertIn('curr_body / curr_range < 0.65', self.market)\n        self.assertIn('curr["volume"] < avg_vol_15m * _vol_threshold', self.market)\n        self.assertIn('not _fast_structure_event', self.market)\n        self.assertIn('(rr < 2.0)', self.market)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
print('RR floor + FAST balanced patch applied')
