from pathlib import Path

# 1) Make the shared Groq wrapper request visible final content from GPT-OSS.
p = Path('market.py')
s = p.read_text(encoding='utf-8')
old = '''                client = Groq(api_key=active_keys[key_index])\n                r = client.chat.completions.create(\n                    model=model,\n                    messages=[{"role": "user", "content": prompt}],\n                    max_tokens=max_tokens,\n                    timeout=30,\n                )\n                _track_tokens(len(prompt) // 4 + max_tokens)\n                _groq_key_index = (key_index + 1) % len(active_keys)\n                return r.choices[0].message.content\n'''
new = '''                client = Groq(api_key=active_keys[key_index])\n                _request_kwargs = {\n                    "model": model,\n                    "messages": [{"role": "user", "content": prompt}],\n                    "timeout": 30,\n                }\n                if str(model).startswith("openai/gpt-oss-"):\n                    # GPT-OSS can spend a small completion budget on hidden reasoning\n                    # and leave message.content empty. Keep reasoning low and request\n                    # only final content for APEX's machine-readable quality gates.\n                    _request_kwargs.update({\n                        "max_completion_tokens": max_tokens,\n                        "reasoning_effort": "low",\n                        "include_reasoning": False,\n                    })\n                else:\n                    _request_kwargs["max_tokens"] = max_tokens\n                r = client.chat.completions.create(**_request_kwargs)\n                _track_tokens(len(prompt) // 4 + max_tokens)\n                content = r.choices[0].message.content or ""\n                if not content.strip():\n                    logging.warning("Groq model %s returned empty final content; trying fallback", model)\n                    continue\n                _groq_key_index = (key_index + 1) % len(active_keys)\n                return content\n'''
if old not in s:
    raise SystemExit('ask_groq request block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# 2) Recover once from a syntactically invalid/non-JSON quality-gate response.
p = Path('core/signal_quality_gate.py')
s = p.read_text(encoding='utf-8')
old = '''    try:\n        raw = await asyncio.wait_for(\n            asyncio.to_thread(ask_groq, prompt, 350),\n            timeout=35,\n        )\n    except Exception as exc:\n        logging.warning("[SignalQualityGate] Groq unavailable: %s", exc)\n        raw = None\n\n    review = _normalize_review(_extract_json(raw), raw)\n    parsed = _extract_json(raw)\n'''
new = '''    try:\n        raw = await asyncio.wait_for(\n            asyncio.to_thread(ask_groq, prompt, 350),\n            timeout=35,\n        )\n    except Exception as exc:\n        logging.warning("[SignalQualityGate] Groq unavailable: %s", exc)\n        raw = None\n\n    parsed = _extract_json(raw)\n    if raw is not None and parsed is None:\n        # The provider answered but the final text was not valid JSON. Retry once\n        # with a compact immutable candidate/assessment contract. This retry is\n        # format recovery only; it cannot alter APEX-calculated trade levels.\n        compact_view = {\n            key: view.get(key) for key in (\n                "symbol", "strategy", "direction", "timeframe", "entry", "sl",\n                "tp1", "tp2", "tp3", "rr", "confluence_score", "regime",\n            )\n        }\n        compact_assessment = {\n            key: setup_assessment.get(key) for key in (\n                "state", "class", "fatal_reasons", "missing", "warnings",\n                "trigger_ready", "geometry_ready", "causal_domains",\n            ) if setup_assessment.get(key) is not None\n        }\n        compact_prompt = f"""You are the final quality reviewer for an already calculated crypto trade candidate.\nDo NOT recalculate or replace entry, SL, TP or RR.\nThe deterministic SETUP EVIDENCE assessment is authoritative: INVALID cannot be approved; DEVELOPING cannot be approved.\n\nCANDIDATE:\n{json.dumps(compact_view, ensure_ascii=False, default=str)}\n\nSETUP EVIDENCE:\n{json.dumps(compact_assessment, ensure_ascii=False, default=str)}\n\nReturn JSON only, with no markdown or commentary:\n{{\n  \\"valid\\": true,\n  \\"decision\\": \\"APPROVE|WAIT|REJECT\\",\n  \\"confidence\\": 0.0,\n  \\"reasons\\": [\\"specific evidence\\"],\n  \\"risks\\": [\\"specific risk\\"]\n}}"""\n        try:\n            retry_raw = await asyncio.wait_for(\n                asyncio.to_thread(ask_groq, compact_prompt, 350),\n                timeout=35,\n            )\n            retry_parsed = _extract_json(retry_raw)\n            if retry_parsed is not None:\n                raw = retry_raw\n                parsed = retry_parsed\n                logging.info("[SignalQualityGate] recovered malformed Groq review with compact JSON retry")\n            else:\n                logging.warning("[SignalQualityGate] Groq parse error after compact retry")\n        except Exception as exc:\n            logging.warning("[SignalQualityGate] compact Groq retry unavailable: %s", exc)\n\n    review = _normalize_review(parsed, raw)\n'''
if old not in s:
    raise SystemExit('quality gate parse block not found')
s = s.replace(old, new, 1)
p.write_text(s, encoding='utf-8')

# 3) Regression coverage for the exact production symptom and immutable levels.
p = Path('tests/test_signal_quality_gate.py')
s = p.read_text(encoding='utf-8')
marker = '''    async def test_low_confidence_approval_waits(self):\n'''
insert = '''    async def test_malformed_first_response_recovers_with_compact_json_retry(self):\n        candidate = {"symbol": "KAITOUSDT", "direction": "BEARISH", "grade": "MTF", "entry": 0.303, "sl": 0.30656, "tp1": 0.2945, "rr": 2.39}\n        calls = []\n        def ask(prompt, tokens):\n            calls.append(prompt)\n            if len(calls) == 1:\n                return "The setup looks acceptable but this is not JSON."\n            return '{"valid":true,"decision":"APPROVE","confidence":0.82,"reasons":["structure and RR valid"],"risks":[]}'\n        with patch("core.signal_quality_gate.collect_external_context", new=AsyncMock(return_value=empty_context("KAITOUSDT"))), \\\n             patch("core.signal_quality_gate.collect_news_context", new=AsyncMock(return_value=empty_news("KAITOUSDT"))), \\\n             patch("core.signal_quality_gate.build_zone_context", return_value=EMPTY_ZONES), \\\n             patch("core.signal_quality_gate.build_learning_context", return_value=EMPTY_LEARNING), \\\n             patch("core.signal_quality_gate.persist_context"), patch("core.signal_quality_gate.persist_news_context"), \\\n             patch("core.signal_quality_gate._persist_review"):\n            review = await review_signal_candidate(candidate, ask)\n        self.assertEqual(len(calls), 2)\n        self.assertLess(len(calls[1]), 6000)\n        self.assertEqual(review["decision"], "APPROVE")\n        self.assertFalse(review["degraded"])\n        self.assertEqual((candidate["entry"], candidate["sl"], candidate["tp1"], candidate["rr"]), (0.303, 0.30656, 0.2945, 2.39))\n\n    async def test_two_malformed_responses_stay_degraded(self):\n        candidate = {"symbol": "KAITOUSDT", "direction": "BEARISH", "grade": "MTF", "entry": 0.303, "sl": 0.30656, "tp1": 0.2945, "rr": 2.39}\n        calls = []\n        def ask(prompt, tokens):\n            calls.append(prompt)\n            return "not json"\n        with patch("core.signal_quality_gate.collect_external_context", new=AsyncMock(return_value=empty_context("KAITOUSDT"))), \\\n             patch("core.signal_quality_gate.collect_news_context", new=AsyncMock(return_value=empty_news("KAITOUSDT"))), \\\n             patch("core.signal_quality_gate.build_zone_context", return_value=EMPTY_ZONES), \\\n             patch("core.signal_quality_gate.build_learning_context", return_value=EMPTY_LEARNING), \\\n             patch("core.signal_quality_gate.persist_context"), patch("core.signal_quality_gate.persist_news_context"), \\\n             patch("core.signal_quality_gate._persist_review"):\n            review = await review_signal_candidate(candidate, ask)\n        self.assertEqual(len(calls), 2)\n        self.assertTrue(review["degraded"])\n        self.assertEqual(review["confidence"], 0.0)\n\n'''
if marker not in s:
    raise SystemExit('signal quality test insertion marker not found')
s = s.replace(marker, insert + marker, 1)
p.write_text(s, encoding='utf-8')

p = Path('tests/test_groq_gpt_oss_output.py')
p.write_text('''import unittest\nfrom pathlib import Path\n\n\nclass GroqGptOssOutputTests(unittest.TestCase):\n    @classmethod\n    def setUpClass(cls):\n        cls.market = Path("market.py").read_text(encoding="utf-8")\n\n    def test_gpt_oss_requests_final_content_not_reasoning_budget(self):\n        self.assertIn('str(model).startswith("openai/gpt-oss-")', self.market)\n        self.assertIn('"max_completion_tokens": max_tokens', self.market)\n        self.assertIn('"reasoning_effort": "low"', self.market)\n        self.assertIn('"include_reasoning": False', self.market)\n\n    def test_empty_final_content_falls_through_to_model_fallback(self):\n        self.assertIn('if not content.strip():', self.market)\n        self.assertIn('returned empty final content; trying fallback', self.market)\n\n    def test_non_gpt_oss_keeps_existing_max_tokens_contract(self):\n        self.assertIn('_request_kwargs["max_tokens"] = max_tokens', self.market)\n\n\nif __name__ == "__main__":\n    unittest.main()\n''', encoding='utf-8')
print('Groq GPT-OSS output patch applied')
