"""Stable APEX V3 architectural constants."""

PRIMARY_MARKET_SOURCE = "GATE"
EXECUTION_SOURCE = "BINANCE"
LIVE_CONTEXT_SOURCE = "LIVE_CONTEXT"
PROXY_SOURCE = "PROXY"

STRATEGY_NAMES = ("FAST", "MTF", "ZONE", "SWING", "WYCKOFF")

JOB_PRIORITY = {
    "BINANCE_PROTECTION": 0,
    "MANAGER": 1,
    "GATE_CRITICAL": 2,
    "SCANNERS": 3,
    "RISK_EXECUTION": 4,
    "TELEGRAM": 5,
    "TELEMETRY": 6,
    "STATE_BACKUP": 7,
    "LEARNING": 8,
    "REPORTS": 9,
}

__all__ = [
    "PRIMARY_MARKET_SOURCE", "EXECUTION_SOURCE", "LIVE_CONTEXT_SOURCE",
    "PROXY_SOURCE", "STRATEGY_NAMES", "JOB_PRIORITY",
]
