from pathlib import Path
p=Path('stats_server.py')
s=p.read_text(encoding='utf-8')
old='''        for ch in r.get("checks",[]) if isinstance(r.get("checks"),list) else []:\n            if isinstance(ch,dict): checks[str(ch.get("label") or ch.get("condition") or ch.get("code") or "check")[:300]][str(ch.get("state") or "UNKNOWN").upper()]+=1'''
new='''        for ch in r.get("checks",[]) if isinstance(r.get("checks"),list) else []:\n            if isinstance(ch,dict):\n                label=str(ch.get("label") or ch.get("condition") or ch.get("code") or "check")[:300]\n                checks[(name,label)][str(ch.get("state") or "UNKNOWN").upper()]+=1'''
assert old in s
s=s.replace(old,new)
old='''      "criterion_stats":[{"label":k,"pass":v.get("PASS",0),"fail":v.get("FAIL",0),"total":v.get("PASS",0)+v.get("FAIL",0)} for k,v in sorted(checks.items(),key=lambda x:sum(x[1].values()),reverse=True)[:200]],'''
new='''      "criterion_stats":[{"strategy":k[0],"label":k[1],"pass":v.get("PASS",0),"fail":v.get("FAIL",0),"total":v.get("PASS",0)+v.get("FAIL",0)} for k,v in sorted(checks.items(),key=lambda x:sum(x[1].values()),reverse=True)[:300]],'''
assert old in s
s=s.replace(old,new)
old="""function renderChecks(){criteriaStats.innerHTML=LAST.criterion_stats.slice(0,35).map(x=>{const p=x.total?Math.round(x.pass/x.total*100):0;return `<div class=barrow><div>${esc(x.label).slice(0,100)}</div><div class=bar><i style=\"width:${p}%\"></i></div><b>${p}%</b></div>`}).join('')||'<span class=muted>Нет данных</span>'}"""
new="""function renderChecks(){const a=LAST.criterion_stats.filter(x=>!STRATEGY||x.strategy===STRATEGY);criteriaStats.innerHTML=a.slice(0,80).map(x=>{const p=x.total?Math.round(x.pass/x.total*100):0;return `<div class=barrow><div><b>${esc(x.strategy)}</b> · ${esc(x.label).slice(0,90)}<div class=muted>✅ ${x.pass} · ❌ ${x.fail} · всего ${x.total}</div></div><div class=bar><i style=\"width:${p}%\"></i></div><b>${p}%</b></div>`}).join('')||'<span class=muted>Нет данных</span>'}"""
assert old in s
s=s.replace(old,new)
start=s.index('function detailText(r){')
end=s.index('}function renderRows()',start)+1
helper=r'''function normText(v){return String(v||'').toLowerCase().replace(/[_/.-]+/g,' ').replace(/[^a-zа-я0-9 ]/gi,' ').replace(/\s+/g,' ').trim()}
function words(v){return new Set(normText(v).split(' ').filter(x=>x.length>2&&!['the','and','for','with','not','или','для','при','что','это'].includes(x)))}
function matchCriterion(q,checks,stop){const qc=normText(q.code),ql=normText(q.label),qw=words(q.code+' '+q.label);let best=null,bestScore=0;for(const ch of checks){const raw=[ch.code,ch.label,ch.condition].filter(Boolean).join(' '),n=normText(raw);let score=0;if(qc&&n.includes(qc))score+=12;if(ql&&n.includes(ql))score+=10;const cw=words(raw);for(const w of qw)if(cw.has(w))score+=1;if(score>bestScore){bestScore=score;best=ch}}if(bestScore>=3)return {state:String(best.state||'UNKNOWN').toUpperCase(),source:best};const st=normText((stop?.code||'')+' '+(stop?.label||'')+' '+(stop?.condition||''));let ss=0;for(const w of qw)if(st.includes(w))ss++;if((qc&&st.includes(qc))||(ql&&st.includes(ql))||ss>=2)return {state:'FAIL',source:stop};return {state:'NOT_REACHED',source:null}}
function sectionName(cat,required){const c=normText(cat);if(/final deterministic|geometry/.test(c))return 'FINAL / GEOMETRY';if(/trigger|structure|phase/.test(c))return 'TRIGGER / STRUCTURE';if(/confirmation|risk context|market context|learning/.test(c))return required?'CORE CONTEXT':'ADDITIONAL';if(/ai quality/.test(c))return 'GROQ';return required?'CORE':'ADDITIONAL'}
function detailText(r){const l=levels(r),g=r.groq_review||{},stop=r.stop||{},snap=stop.snapshot||{},checks=Array.isArray(r.checks)?r.checks:[],catalog=(LAST.catalog||{})[r.strategy]||{criteria:[]};const dir=String(r.candidate?.direction??snap.direction??'').toUpperCase()||'—';const lines=[`${r.symbol||'—'} · ${r.strategy||'—'} · ${dir}`,(r.finished_at||r.occurred_at||'').replace('T',' ').slice(0,19)+' UTC',''];const groups={};let pass=0,fail=0,nr=0,opt=0;for(const q of (catalog.criteria||[])){let m=matchCriterion(q,checks,stop);if(q.code.endsWith('_groq'))m=g.decision?{state:String(g.decision).toUpperCase()==='APPROVE'?'PASS':'FAIL'}:{state:'NOT_REACHED'};const group=sectionName(q.category,q.required);if(!groups[group])groups[group]=[];const state=m.state,icon=state==='PASS'?'✅':state==='FAIL'?'❌':'⏭';if(state==='PASS')pass++;else if(state==='FAIL')fail++;else nr++;if(!q.required)opt++;groups[group].push(`${icon} ${q.required?'[MAIN]':'[ADD]'} ${q.label}${state==='NOT_REACHED'?' · not reached':''}`)}lines.push(`[SUMMARY]`,`✅ Passed: ${pass} · ❌ Failed: ${fail} · ⏭ Not reached: ${nr} · ADD criteria: ${opt}`,'');for(const k of ['CORE','CORE CONTEXT','TRIGGER / STRUCTURE','ADDITIONAL','FINAL / GEOMETRY','GROQ'])if(groups[k]?.length)lines.push(`[${k}]`,...groups[k],'');const matched=new Set();for(const q of (catalog.criteria||[])){const m=matchCriterion(q,checks,stop);if(m.source)matched.add(m.source)}const extras=checks.filter(ch=>!matched.has(ch)&&!String(ch.code||'').startsWith('_')&&!String(ch.label||'').startsWith('_'));if(extras.length){lines.push('[OTHER RECORDED CHECKS]');for(const ch of extras){const st=String(ch.state||'UNKNOWN').toUpperCase();lines.push(`${st==='PASS'?'✅':st==='FAIL'?'❌':'⚠️'} ${ch.label||ch.condition||ch.code}`)}lines.push('')}lines.push('[LEVELS]',`Entry: ${num(l.entry)}`,`SL:    ${num(l.sl)}`,`TP1:   ${num(l.tp1)}`,`TP2:   ${num(l.tp2)}`,`TP3:   ${num(l.tp3)}`,`RR:    ${num(l.rr)}`,'');if(g.decision){lines.push('[GROQ RESULT]',`Decision: ${g.decision}`,`Confidence: ${g.confidence!==undefined?Math.round(Number(g.confidence)*100)+'%':'—'}`);if(Array.isArray(g.reasons)&&g.reasons.length)lines.push('Reasons:',...g.reasons.map(x=>'❌ '+x));if(Array.isArray(g.risks)&&g.risks.length)lines.push('Risks:',...g.risks.map(x=>'⚠️ '+x));lines.push('')}else lines.push('[GROQ RESULT]','⏭ Not reached','');lines.push('[STOP]',stop.label||stop.code||'—');return lines.join('\n')}
'''
s=s[:start]+helper+s[end:]
p.write_text(s,encoding='utf-8')
